name: CI with Jira and Slack Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check tests directory
        run: ls -la tests/ || echo "Tests directory not found"
      - name: Run tests
        run: pytest tests/ --verbose

  update-jira:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract Jira issue key
        id: extract-jira
        run: |
          ISSUE_KEY=$(git log -1 --pretty=%B | grep -oE '[A-Z]+-[0-9]+' | head -1)
          if [ -z "$ISSUE_KEY" ]; then
            echo "No Jira issue key found"
            exit 0
          fi
          echo "issue_key=$ISSUE_KEY" >> $GITHUB_OUTPUT
      - name: Login to Jira
        if: steps.extract-jira.outputs.issue_key
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: "https://sondanghuynh-1744373051968.atlassian.net"
          JIRA_USER_EMAIL: "sondanghuynh@gmail.com"
          JIRA_API_TOKEN: "ATATT3xFfGF0Ki433J3MN4rYm6wuUCoxBIN00gQ8j3MklIpXvF7XTsQQ6g9L__BV4LUUQGxAVHJ3NTV9yw-8W80Lylkz2Ivu3NmxVQO2n6s6gmtAVye_O4hyWn8_g7FgNGE_Q3bfNCNanPT3eSX5mvrJwA4Hp-XWlJc4OQ55s0n67kGDW-f3yP4=67394863"
      - name: Transition Jira issue
        if: steps.extract-jira.outputs.issue_key
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.extract-jira.outputs.issue_key }}
          transition: Done
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}

  notify-slack:
    needs: update-jira
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract Jira issue key
        id: extract-jira
        run: |
          ISSUE_KEY=$(git log -1 --pretty=%B | grep -oE '[A-Z]+-[0-9]+' | head -1)
          if [ -z "$ISSUE_KEY" ]; then
            echo "No Jira issue key found"
            exit 0
          fi
          echo "issue_key=$ISSUE_KEY" >> $GITHUB_OUTPUT
      - name: Send Slack notification
        if: steps.extract-jira.outputs.issue_key
        uses: slackapi/slack-github-action@v1.27.0
        with:
          slack-bot-token: ${{ CICD.SLACK_BOT_TOKEN }}
          channel-id: 'C12345678' # Replace with your #cicd-notifications channel ID
          text: 'Jira issue ${{ steps.extract-jira.outputs.issue_key }} has been closed successfully!'
